name: "[M] Plugin and CLI: publish as archives"

on: 
  workflow_dispatch:
    inputs:
        version-postfix:
          type: choice
          description: "It adds alpha or beta postfix to version."
          required: true
          default: no-postfix
          options:
          - no-postfix
          - alpha
          - beta

env:
  GIT_USERNAME: bot
  # repo name in events doesn't fit our requirements because contains slash symbol
  # https://docs.github.com/en/developers/webhooks-and-events/events/github-event-types
  GIT_REPO_NAME: UTBotJava
  SSL_CERT_DIR: /etc/ssl/certs

jobs:
    publish_plugin_and_cli:
      runs-on: [self-hosted, local]
      #runs-on: ubuntu-latest
      container:
        image: ubuntu:20.04
        volumes:
          - /home/github-runner/certificates/:/usr/local/share/ca-certificates/
      
      steps:
      - name: Install prerequisites
        run: |
          set -x
          apt update
          apt install -y unzip \
                         fonts-dejavu \
                         fontconfig \
                         git \
                         ca-certificates
          cp /usr/local/share/ca-certificates/* /etc/ssl/certs/
          update-ca-certificates

#      - uses: actions/checkout@v3
      - name: User payload | Checkout repository
        run: |
          set -x
          git config --global credential.helper 'store --file ~/.git-credentials'
          echo "https://${GIT_USERNAME}:${GITHUB_TOKEN}@github.com" > ~/.git-credentials
          git clone https://github.com/UnitTestBot/${GIT_REPO_NAME}.git ${GIT_REPO_NAME}
          cd ${GIT_REPO_NAME}
          git checkout ${GITHUB_REF_NAME}
          ls -lh

      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
          java-package: jdk+fx
          cache: gradle
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.8
          
      - name: Set environment variables
        run: |
          echo "VERSION="$(date +%Y).$(date +%-m)"" >> $GITHUB_ENV
          echo "POSTFIX=${{ github.event.inputs.version-postfix }}" >> $GITHUB_ENV
          
      - name: Create version with postfix
        if: ${{ (env.POSTFIX == 'alpha') || (env.POSTFIX == 'beta') }}
        run:
          echo "VERSION=${{ env.VERSION }}-${{ env.POSTFIX }}" >> $GITHUB_ENV
          
      - name: Build UTBot IntelliJ IDEA plugin
        run: |
          export KOTLIN_HOME="/usr"
          gradle buildPlugin --no-daemon -PsemVer=${{ env.VERSION }}
          cd utbot-intellij/build/distributions
          unzip utbot-intellij-${{ env.VERSION }}.zip
          
      - name: Archive UTBot IntelliJ IDEA plugin
        uses: actions/upload-artifact@v2
        with:
          name: utbot-intellij-${{ env.VERSION }}
          path: utbot-intellij/build/distributions/*
          
      - name: Build UTBot CLI
        run: |
          export KOTLIN_HOME="/usr"
          cd utbot-cli
          gradle clean build --no-daemon -PsemVer=${{ env.VERSION }}
          cd build/libs
          
      - name: Archive UTBot CLI
        uses: actions/upload-artifact@v2
        with:
          name: utbot-cli-${{ env.VERSION }}
          path: utbot-cli/build/libs/utbot-cli-${{ env.VERSION }}.jar
